name: Ejecuci√≥n de tests joyeria wilma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Instalar dependencias y navegadores
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Ejecutar tests Playwright (con Allure)
        run: |
          npx playwright test

      - name: Generar reporte Allure
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Publicar Allure Report en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
